LABEL_MAP = {
    "avg_words_per_sentence": "mean words per sentence",
    "avg_syllables_per_word": "mean syllables per word",
    "flesch_reading_ease": "FRE",
    "flesch_kincaid_grade": "FKGL",
    "flesh_reading_ease": "FRE",
    "dale_chall": "Dale-Chall",
    "smog_index": "SMOG",
    "automated_readability_index": "ARI",
    "gunning_fog": "Gunning Fog",
    "hedge_ratio": "hedge terms",
    "certainty_ratio": "certainty terms",
    "colon_per_1k_words": "colon",
    "semicolon_per_1k_words": "semicolon",
    "em_dash_per_1k_words": "em dash",
    "word_count": "word count",
    "sentence_count": "sentence count",
    "clause_depth": "clause depth",
    "clause_depth_std": "clause depth (std)",
    "contrast_marker_however_per_1k_words": "`however`",
    "verb_exhibit_per_1k_words": "`exhibit`",
    "verb_delve_per_1k_words": "`delve`",
    "verb_underscore_per_1k_words": "`underscore`",
    "verb_showcase_per_1k_words": "`showcase`",
    "verb_enhance_per_1k_words": "`enhance`",
    "verb_garner_per_1k_words": "`garner`",
    "verb_align_per_1k_words": "`align`",
    "verb_foster_per_1k_words": "`foster`",
    "adjective_potential_per_1k_words": "`potential`",
    "adjective_comprehensive_per_1k_words": "`comprehensive`",
    "adjective_intricate_per_1k_words": "`intricate`",
    "adjective_crucial_per_1k_words": "`crucial`",
    "adjective_pivotal_per_1k_words": "`pivotal`",
    "list_of_three_per_1k_words": "list of three",
    "list_of_three": "list of three",
    "sequential_markers_total_per_1k_words": "sequential markers",
    "emphasis_markers_total_per_1k_words": "emphasis markers",
    "causal_markers_total_per_1k_words": "causal markers",
    "contrast_markers_total_per_1k_words": "contrast markers",
    "summary_markers_total_per_1k_words": "summary markers",
    "coordination_count": "coordination count",
    "coordination_per_sentence_std": "coordination per sentence (std)",
    "marker_words_total_per_1k_words": "marker words",
    "phrase_meticulously_delve_per_1k_words": "`meticulously delve`",
    "phrase_intricate_web_per_1k_words": "`intricate web`",
    "phrase_comprehensive_chapter_per_1k_words": "`comprehensive chapter`",
    "phrase_deep_dive_per_1k_words": "`deep dive`",
    "phrase_intricate_interplay_per_1k_words": "`intricate interplay`",
    "phrase_essential_insight_per_1k_words": "`essential insight`",
    "word_insight_per_1k_words": "`insight`",
    "word_finding_per_1k_words": "`finding`",
    "word_interplay_per_1k_words": "`interplay`",
    "word_realm_per_1k_words": "`realm`",
    "word_notably_per_1k_words": "`notably`",
    "word_particularly_per_1k_words": "`particularly`",
    "word_meticulously_per_1k_words": "`meticulously`",
    "word_while_per_1k_words": "`while`",
    "word_within_per_1k_words": "`within`",
    "word_across_per_1k_words": "`across`",
    "word_additionally_per_1k_words": "`additionally`",
}
