LABEL_MAP = {
    "avg_words_per_sentence": "mean words per sentence",
    "avg_syllables_per_word": "mean syllables per word",
    "flesch_reading_ease": "FRE",
    "flesch_kincaid_grade": "FKGL",
    "flesh_reading_ease": "FRE",
    "dale_chall": "Dale-Chall",
    "smog_index": "SMOG",
    "automated_readability_index": "ARI",
    "gunning_fog": "Gunning Fog",
    "hedge_ratio": "hedge terms",
    "certainty_ratio": "certainty terms",
    "colon_per_1k_words": "colon",
    "semicolon_per_1k_words": "semicolon",
    "em_dash_per_1k_words": "em dash",
    "word_count": "word count",
    "sentence_count": "sentence count",
    "clause_depth": "clause depth",
    "clause_depth_std": "clause depth (std)",
    "contrast_marker_however_per_1k_words": "`however`",
    "verb_exhibit_per_1k_words": "`exhibit`",
    "verb_delve_per_1k_words": "`delve`",
    "verb_underscore_per_1k_words": "`underscore`",
    "verb_showcase_per_1k_words": "`showcase`",
    "verb_enhance_per_1k_words": "`enhance`",
    "verb_garner_per_1k_words": "`garner`",
    "verb_align_per_1k_words": "`align`",
    "verb_foster_per_1k_words": "`foster`",
    "adjective_potential_per_1k_words": "`potential`",
    "adjective_comprehensive_per_1k_words": "`comprehensive`",
    "adjective_intricate_per_1k_words": "`intricate`",
    "adjective_crucial_per_1k_words": "`crucial`",
    "adjective_pivotal_per_1k_words": "`pivotal`",
    "list_of_three_per_1k_words": "list of three",
    "list_of_three": "list of three",
    "sequential_markers_total_per_1k_words": "sequential markers",
    "emphasis_markers_total_per_1k_words": "emphasis markers",
    "causal_markers_total_per_1k_words": "causal markers",
    "contrast_markers_total_per_1k_words": "contrast markers",
    "summary_markers_total_per_1k_words": "summary markers",
    "coordination_count": "coordination count",
    "coordination_per_sentence_std": "coordination per sentence (std)",
    "marker_words_total_per_1k_words": "marker words",
    "phrase_meticulously_delve_per_1k_words": "`meticulously delve`",
    "phrase_intricate_web_per_1k_words": "`intricate web`",
    "phrase_comprehensive_chapter_per_1k_words": "`comprehensive chapter`",
    "phrase_deep_dive_per_1k_words": "`deep dive`",
    "phrase_intricate_interplay_per_1k_words": "`intricate interplay`",
    "phrase_essential_insight_per_1k_words": "`essential insight`",
    "word_insight_per_1k_words": "`insight`",
    "word_finding_per_1k_words": "`finding`",
    "word_interplay_per_1k_words": "`interplay`",
    "word_realm_per_1k_words": "`realm`",
    "word_notably_per_1k_words": "`notably`",
    "word_particularly_per_1k_words": "`particularly`",
    "word_meticulously_per_1k_words": "`meticulously`",
    "word_while_per_1k_words": "`while`",
    "word_within_per_1k_words": "`within`",
    "word_across_per_1k_words": "`across`",
    "word_additionally_per_1k_words": "`additionally`",
    "sequential_marker_additionally_per_1k_words": "`additionally`",
    "sequential_marker_furthermore_per_1k_words": "`furthermore`",
    "sequential_marker_moreover_per_1k_words": "`moreover`",
    "sequential_marker_subsequently_per_1k_words": "`subsequently`",
    "sequential_marker_further_per_1k_words": "`further`",
    "causal_marker_hence_per_1k_words": "`hence`",
    "causal_marker_thus_per_1k_words": "`thus`",
    "causal_marker_consequently_per_1k_words": "`consequently`",
    "causal_marker_accordingly_per_1k_words": "`accordingly`",
    "causal_marker_thereby_per_1k_words": "`thereby`",
    "contrast_marker_however_per_1k_words": "`however`",
    "contrast_marker_nonetheless_per_1k_words": "`nonetheless`",
    "contrast_marker_nevertheless_per_1k_words": "`nevertheless`",
    "contrast_marker_conversely_per_1k_words": "`conversely`",
    "contrast_marker_alternatively_per_1k_words": "`alternatively`",
    "emphasis_marker_notably_per_1k_words": "`notably`",
    "emphasis_marker_crucially_per_1k_words": "`crucially`",
    "emphasis_marker_remarkably_per_1k_words": "`remarkably`",
    "emphasis_marker_particularly_per_1k_words": "`particularly`",
    "emphasis_marker_importantly_per_1k_words": "`importantly`",
    "summary_marker_overall_per_1k_words": "`overall`",
    "summary_marker_collectively_per_1k_words": "`collectively`",
    "summary_marker_ultimately_per_1k_words": "`ultimately`",
    "summary_marker_in_summary_per_1k_words": "`in summary`",
    "summary_marker_taken_together_per_1k_words": "`taken together`",
}


def pretty_feature_label(feature: str, label_map: dict[str, str] | None = None) -> str:
    label_map = label_map or LABEL_MAP
    mapped = label_map.get(feature, feature)
    return mapped


def _uses_angle_brackets(feature: str, mapped: str) -> bool:
    lexical_prefixes = ("word_", "verb_", "adjective_", "phrase_")
    marker_prefixes = (
        "sequential_marker_",
        "causal_marker_",
        "contrast_marker_",
        "emphasis_marker_",
        "summary_marker_",
    )
    marker_totals = (
        "marker_words_total_per_1k_words",
        "marker_verbs_total_per_1k_words",
        "marker_adjectives_total_per_1k_words",
        "marker_phrases_total_per_1k_words",
        "sequential_markers_total_per_1k_words",
        "causal_markers_total_per_1k_words",
        "contrast_markers_total_per_1k_words",
        "emphasis_markers_total_per_1k_words",
        "summary_markers_total_per_1k_words",
    )
    return (
        "`" in mapped
        or feature.startswith(lexical_prefixes)
        or feature.startswith(marker_prefixes)
        or feature in marker_totals
    )
